export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';
export const GET_INITIAL_COUNT_START = 'GET_INITIAL_COUNT_START';
export const GET_INITIAL_COUNT_SUCCESS = 'GET_INITIAL_COUNT_SUCCESS';
export const GET_INITIAL_COUNT_ERROR = 'GET_INITIAL_COUNT_ERROR';